#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: F://IDEA/sell/log/sell.log

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1994
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell